version: '1'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    volumes:
      - ./mysql_data:/var/lib/mysql

  php:
    image: php:apache
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
